plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-berry.js

packageExtensions:
  "sax@*":
    dependencies:
      stream-browserify: "*"
      buffer: "*"
  "react-transition-group@*":
    dependencies:
      react-dom: "*"
  "react-toastify@*":
    dependencies:
      react-dom: "*"
  "react-multi-carousel@*":
    dependencies:
      react: "*"
  "@testing-library/react@*":
    dependencies:
      react-dom: "*"
