plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-berry.js

bstatePath: "/yarn/build-state.yml"
cacheFolder: "/yarn/cache"
globalFolder: "/yarn/global"
virtualFolder: "/yarn/__virtual__"
pnpUnpluggedFolder: "/yarn/unplugged"
