packageExtensions:
  "@testing-library/react@*":
    dependencies:
      react-dom: "*"
  react-multi-carousel@*:
    dependencies:
      react: "*"
  react-toastify@*:
    dependencies:
      react-dom: "*"
  react-transition-group@*:
    dependencies:
      react-dom: "*"
  sax@*:
    dependencies:
      buffer: "*"
      stream-browserify: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
