apiVersion: v1
name: openneuro
version: 1.2.0
description: OpenNeuro production deployment chart
home: https://openneuro.org
sources:
  - https://github.com/openNeuroOrg/openneuro
<<<<<<< Updated upstream
appVersion: 4.16.0
=======
appVersion: 4.16.1
>>>>>>> Stashed changes
dependencies:
  - name: redis
    version: 17.1.4
    repository: https://charts.bitnami.com/bitnami
