# Root hostname
hostname: openneuro.staging.sqm.io

# The FQDN URL for the site, optionally including port number
url: https://openneuro.staging.sqm.io

# A unique string identifying this install of OpenNeuro
environment: staging

# Enable FreshDesk ticketing
freshDeskUrl: https://openneuro.freshdesk.com/widgets/feedback_widget/new?&widgetType=embedded&screenshot=no

# Enable Google Analytics
googleTrackingId: UA-100754266-1

# AWS TLS Certificate ARN
certifcateArn: "arn:aws:acm:us-east-1:488777458602:certificate/6883342b-63ac-4466-b3f8-d9a8dd80bfaa"

# Dataset worker parallelism
dataladWorkers: 4

# Content container tag
contentTag: v1.0.1

# The underlying EFS volume should be created manually and configured here
efs-provisioner:
  efsProvisioner:
    awsRegion: us-east-1
    efsFileSystemId: fs-acb10b4f
    path: /pv
    storageClass:
      reclaimPolicy: Retain

# Load balancer / ingress config
aws-alb-ingress-controller:
  awsRegion: us-east-1
  autoDiscoverAwsVpcID: true
  clusterName: openneuro-staging

# Disable Redis password for testing
redis:
  usePassword: false
  master:
    disableCommands: []
    resources:
      limits:
        cpu: "500m"
        memory: "1000Mi"
      requests:
        cpu: "250m"
        memory: "500Mi"
  slave:
    resources:
      limits:
        cpu: "250m"
        memory: "768Mi"
      requests:
        cpu: "125m"
        memory: "256Mi"
