# Root hostname
hostname: openneuro.org

# The FQDN URL for the site, optionally including port number
url: https://openneuro.org

# GraphQL endpoint
graphql: https://openneuro.org/crn/graphql

# A unique string identifying this install of OpenNeuro
environment: production

# Enable FreshDesk ticketing
freshDeskUrl: https://openneuro.freshdesk.com/widgets/feedback_widget/new?&widgetType=embedded&screenshot=no

# Enable Google Analytics
googleTrackingId: UA-100754266-2

# AWS TLS Certificate ARN
certifcateArn: "arn:aws:acm:us-west-2:488777458602:certificate/d37b43e0-9af3-423a-86ef-0652e0332e33"

# Dataset worker parallelism
dataladWorkers: 4

# OpenNeuro-server API parallelism
apiReplicas: 4

# Static service parallelism
webReplicas: 4

# Content container tag
contentTag: v1.0.3

# Sentry DSN (non-secret version)
sentryDsn: https://ba0c58863b3e40a2a412132bfd2711ea@o114074.ingest.sentry.io/251076

# Configure storage node EBS volumes
# Workers are evenly distributed across available pools
# Size in bytes
storagePools:
  # This is the size of the pool disks
  stripeSize: 17592186044416
  pools:
    - name: a
      size: 16492674416640
    - name: b
      size: 16492674416640

# The underlying EFS volume should be created manually and configured here
efs-provisioner:
  efsProvisioner:
    awsRegion: us-east-1
    efsFileSystemId: fs-9d8a877e
    path: /pv
    storageClass:
      reclaimPolicy: Retain

# Load balancer / ingress config
aws-alb-ingress-controller:
  awsRegion: us-west-2
  autoDiscoverAwsVpcID: true
  clusterName: openneuro-prod

# Disable Redis password for testing
redis:
  usePassword: false
  master:
    disableCommands: []
    persistence:
      size: 40Gi
    statefulset:
      updateStrategy: RollingUpdate
    resources:
      limits:
        cpu: "2"
        memory: "8Gi"
      requests:
        cpu: "500m"
        memory: "4Gi"
  slave:
    persistence:
      size: 40Gi
    statefulset:
      updateStrategy: RollingUpdate
    resources:
      limits:
        cpu: "2"
        memory: "8Gi"
      requests:
        cpu: "500m"
        memory: "4Gi"
