# Root hostname
hostname: openneuro.org

# The FQDN URL for the site, optionally including port number
url: https://openneuro.org

# GraphQL endpoint
graphql: http://openneuro-prod-api:8111/crn/graphql

# A unique string identifying this install of OpenNeuro
environment: production

# Enable FreshDesk ticketing
freshDeskUrl: https://openneuro.freshdesk.com/widgets/feedback_widget/new?&widgetType=embedded&screenshot=no

# Enable Google Analytics
googleTrackingIds: 'UA-100754266-2,G-MJNMY6D3FX'

# AWS TLS Certificate ARN
certifcateArn: "arn:aws:acm:us-west-2:488777458602:certificate/d37b43e0-9af3-423a-86ef-0652e0332e33"

# Dataset worker parallelism
dataladWorkers: 4

# OpenNeuro-server API parallelism
apiReplicas: 8

# Static service parallelism
webReplicas: 6

# Content container tag
contentTag: v1.0.6

# Sentry DSN (non-secret version)
sentryDsn: https://ba0c58863b3e40a2a412132bfd2711ea@o114074.ingest.sentry.io/251076

# Elastic APM path
apmServerUrl: https://17ae1d2cfa8f47f486b1b6fda3ed9f43.apm.us-west-2.aws.found.io

# Worker CPU requests
workerCpuRequests: 2

# Configure storage node EBS volumes
# Workers are evenly distributed across available pools
# Size in bytes
storagePools:
  # This is the size of the pool disks
  stripeSize: 17592186044416
  pools:
    - name: a
      size: 16492674416640
    - name: b
      size: 32985348833280

# The underlying EFS volume should be created manually and configured here
efs-provisioner:
  efsProvisioner:
    awsRegion: us-east-1
    efsFileSystemId: fs-9d8a877e
    path: /pv
    storageClass:
      reclaimPolicy: Retain

# Load balancer / ingress config
aws-alb-ingress-controller:
  awsRegion: us-west-2
  autoDiscoverAwsVpcID: true
  clusterName: openneuro-prod-2021

# Disable Redis password for testing
redis:
  usePassword: false
  master:
    disableCommands: []
    persistence:
      size: 40Gi
    statefulset:
      updateStrategy: RollingUpdate
    resources:
      limits:
        cpu: "2"
        memory: "8Gi"
      requests:
        cpu: "500m"
        memory: "2Gi"
  slave:
    persistence:
      size: 40Gi
    statefulset:
      updateStrategy: RollingUpdate
    resources:
      limits:
        cpu: "2"
        memory: "8Gi"
      requests:
        cpu: "500m"
        memory: "2Gi"

apm-server:
  apmConfig:
    apm-server.yml: |
      apm-server:
        host: "0.0.0.0:8200"
        rum.enabled: true
      queue: {}
      cloud:
        id: "${ELASTICSEARCH_CLOUD_ID}"
        auth: "${ELASTICSEARCH_CLOUD_AUTH}"
  envFrom:
    - secretRef:
        name: openneuro-prod-secret
