version: 2

jobs:
  build:
    working_directory: ~/OpenNeuroOrg/openneuro
    docker:
      - image: circleci/node:8.11-jessie-browsers
    steps:
      - checkout
      - save_cache:
          key: dependency-cache
          paths:
            - ~/.cache/yarn
            - ~/.mongodb-binaries
      - run:
          name: yarn install
          command: yarn install
      - run:
          name: lerna bootstrap
          command: yarn bootstrap
      - run:
          name: eslint
          command: yarn lint
      - run:
          name: jest unit coverage
          # Workaround https://github.com/facebook/jest/issues/6506
          # TODO: Switch back to -w 2 after upstream fix
          command: yarn coverage -i --no-cache --forceExit
      - run:
          name: codecov
          command: yarn run codecov

  cli-install-test:
    working_directory: ~/OpenNeuroOrg/openneuro/packages/openneuro-cli
    docker:
      - image: circleci/node:8.11-jessie-browsers
    steps:
      - checkout
      - run: yarn
      - run: yarn openneuro

  app-build:
    working_directory: ~/OpenNeuroOrg/openneuro
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: build openneuro-app
          command: docker build --pull -t openneuro/app -f packages/openneuro-app/Dockerfile .
      - run:
          name: docker tag + push (master)
          command: |
            if [ -z "${CIRCLE_TAG}" ] && [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker tag openneuro/app openneuro/app:latest
              docker push openneuro/app
            fi
      - run:
          name: docker tag + push (branch)
          command: |
            if [ -z "${CIRCLE_TAG}" ] && [ "${CIRCLE_BRANCH}" != "master" ]; then
              docker tag openneuro/app "openneuro/app:${CIRCLE_BRANCH}"
              docker push "openneuro/app:${CIRCLE_BRANCH}"
            fi
      - run:
          name: docker tag + push (tag)
          command: |
            if [ "${CIRCLE_TAG}" ]; then
              docker tag openneuro/app "openneuro/app:${CIRCLE_TAG}"
              docker push "openneuro/app:${CIRCLE_TAG}"
            fi

  server-build:
    working_directory: ~/OpenNeuroOrg/openneuro
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: build openneuro-server
          command: docker build --pull -t openneuro/server packages/openneuro-server
      - run:
          name: docker tag + push (master)
          command: |
            if [ -z "${CIRCLE_TAG}" ] && [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker tag openneuro/server openneuro/server:latest
              docker push openneuro/server
            fi
      - run:
          name: docker tag + push (branch)
          command: |
            if [ -z "${CIRCLE_TAG}" ] && [ "${CIRCLE_BRANCH}" != "master" ]; then
              docker tag openneuro/server "openneuro/server:${CIRCLE_BRANCH}"
              docker push "openneuro/server:${CIRCLE_BRANCH}"
            fi
      - run:
          name: docker tag + push (tag)
          command: |
            if [ "${CIRCLE_TAG}" ]; then
              docker tag openneuro/server "openneuro/server:${CIRCLE_TAG}"
              docker push "openneuro/server:${CIRCLE_TAG}"
            fi

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      - cli-install-test:
          filters:
            tags:
              only: /^v.*/
      - app-build:
          requires:
            - build
            - cli-install-test
          filters:
            tags:
              only: /^v.*/
      - server-build:
          requires:
            - build
            - cli-install-test
          filters:
            tags:
              only: /^v.*/
