name: Tracking datasets
description: Track specific datasets affected by a similar bug
labels:
  - "Tracking"

body:
  - type: textarea
    id: datasets
    attributes:
      label: Dataset issue
      description: Describe the issue that appears to be affecting these datasets
    validations:
      required: true
  - type: textarea
    id: tracker
    attributes:
      label: The following datasets are affected
      description: |
        Please list below all affected datasets and add any additional information unique to that dataset.
        Check each off as it is resolved.
      placeholder: |
        - [ ] ds0 , reported on `<date>` (also affected by: )
        - [ ] ds1 , reported on `<date>` (also affected by: )
    validations:
      required: true
