apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: openneuro-staging
  region: us-east-1

nodeGroups:
  - name: general
    instanceType: m5ad.large
    desiredCapacity: 3
    ssh:
      allow: true
