apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: openneuro-prod-2021
  region: us-west-2
  version: "1.19"
availabilityZones:
  - us-west-2b
  - us-west-2c
nodeGroups:
  - name: general
    amiFamily: Ubuntu2004
    instanceType: mixed
    desiredCapacity: 3
    minSize: 2
    maxSize: 6
    instancesDistribution:
      maxPrice: 0.075
      instanceTypes: ["r5a.large"]
      onDemandBaseCapacity: 2
      spotInstancePools: 2
    availabilityZones:
      - us-west-2b
      - us-west-2c
    iam:
      withAddonPolicies:
        ebs: true
        efs: true
        albIngress: true
        certManager: true
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/openneuro-prod-nodegroup.pub
    preBootstrapCommands:
      - apt update
      - apt install -y nfs-common zfsutils-linux
  - name: storage-m5
    amiFamily: Ubuntu2004
    instanceType: m5ad.2xlarge
    desiredCapacity: 2
    labels: { role: storage }
    availabilityZones:
      - us-west-2b
      - us-west-2c
    iam:
      withAddonPolicies:
        ebs: true
        efs: true
        albIngress: true
        certManager: true
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/openneuro-prod-nodegroup.pub
    taints:
      storage: "true:NoSchedule"
    preBootstrapCommands:
      - apt update
      - apt install -y nfs-common zfsutils-linux
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
