apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: {{ .Release.Name }}-api
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /crn/
spec:
  ports:
  - port: 8111
    protocol: TCP
  selector:
    app: {{ .Release.Name }}-api
