apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  CRN_SERVER_URL: {{ .Values.url | quote }}
  GRAPHQL_URI: {{ .Values.graphql | quote }}
  DATALAD_WORKERS: {{ .Values.dataladWorkers | quote }}
  FRESH_DESK_URL: {{ .Values.freshDeskUrl | quote }}
  ENVIRONMENT: {{ .Values.environment | quote }}
  GOOGLE_TRACKING_ID: {{ .Values.googleTrackingId | quote }}
  REDIS_HOST: {{ .Release.Name }}-redis-master
  REDIS_PORT: "6379"
  GRAPHQL_ENDPOINT: http://{{ .Release.Name }}-api:8111/crn/graphql
  DATALAD_SERVICE_URI: {{ .Release.Name }}-dataset-worker
  DATALAD_S3_PUBLIC_ON_EXPORT: "yes"
  LOCPATH: ""
  SENTRY_DSN: {{ .Values.sentryDsn | quote }}
  ELASTIC_APM_SERVER_URL: http://{{ .Release.Name }}-apm-server:8200
  ELASTIC_APM_SERVICE_NAME: openneuro-server
