apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-dataset-worker
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-dataset-worker # has to match .spec.template.metadata.labels
  serviceName: "dataset-worker"
  replicas: {{ .Values.dataladWorkers }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-dataset-worker # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: {{ .Release.Name }}-dataset-worker
        image: 'openneuro/datalad-service:v{{ .Chart.AppVersion }}'
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-configmap
        - secretRef:
            name: {{ .Release.Name }}-secret
        volumeMounts:
        - name: datasets
          mountPath: /datasets
  volumeClaimTemplates:
  - metadata:
      name: {{ .Release.Name }}-datasets
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "efs"
      resources:
        requests:
          storage: 1Gi # This is not used with EFS but we have to ask for it