apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-datalad-service
  labels:
    app: {{ .Release.Name }}-datalad-service
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - port: 9877
    protocol: TCP
  selector:
    app: {{ .Release.Name }}-datalad-service
