apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-datalad-service
  labels:
    app: {{ .Release.Name }}-datalad-service
    chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
    release: '{{ .Release.Name }}'
    heritage: '{{ .Release.Service }}'
spec:
  replicas: 4
  selector:
    matchLabels:
      app: {{ .Release.Name }}-datalad-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-datalad-service
    spec:
      containers:
      - name: {{ .Release.Name }}-datalad-service
        image: 'openneuro/datalad-service:v{{ .Chart.AppVersion }}'
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-configmap
        - secretRef:
            name: {{ .Release.Name }}-secret

