apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-flower
  labels:
    app: {{ .Release.Name }}-flower
    chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
    release: '{{ .Release.Name }}'
    heritage: '{{ .Release.Service }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-flower
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-flower
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      containers:
      - name: {{ .Release.Name }}-flower
        image: 'openneuro/datalad-service:v{{ .Chart.AppVersion }}'
        resources:
          limits:
            cpu: "100m"
            memory: "1024Mi"
          requests:
            cpu: "50m"
            memory: "512Mi"
        ports:
        - containerPort: 5555
        command:
          - flower
          - -A
          - datalad_service.worker
          - --broker
          - redis://{{ .Release.Name }}-redis-master
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-configmap
        - secretRef:
            name: {{ .Release.Name }}-secret
