apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .Release.Name }}
    kubernetes.io/ingress.class: gce
    networking.gke.io/managed-certificates: {{ .Release.Name }}-managed-cert
    networking.gke.io/v1beta1.FrontendConfig: {{ .Release.Name }}-frontend-config
spec:
  rules:
    - host: {{ .Values.hostname }}
      http:
        paths:
          - path: /graphql-subscriptions
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-api
                port:
                  number: 8111
          - path: /crn/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-api
                port:
                  number: 8111
          - path: /sitemap.xml
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-api
                port:
                  number: 8111
          {{- $relname := .Release.Name -}}
          {{- range until ( .Values.dataladWorkers | int ) }}
          - path: /uploads/{{ . }}/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $relname }}-dataset-worker-{{ . }}
                port:
                  number: 80
          {{- end }}
          {{- $relname := .Release.Name -}}
          {{- range until ( .Values.dataladWorkers | int ) }}
          - path: /git/{{ . }}/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $relname }}-dataset-worker-{{ . }}
                port:
                  number: 80
          {{- end }}
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-web
                port:
                  number: 80
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: {{ .Release.Name }}-frontend-config
spec:
  redirectToHttps:
    enabled: true
