{{- $relname := .Release.Name -}}
{{- $stripesize := int .Values.storagePools.stripeSize }}
{{- range .Values.storagePools.pools }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $relname }}-storage-pool-{{ .name }}
spec:
  replicas: {{ ceil (div (int .size) $stripesize)  }}
  selector:
    matchLabels:
      app: {{ $relname }}-storage-pool-{{ .name }}
  serviceName: {{ $relname }}-storage-pool-{{ .name }}
  template:
    metadata:
      labels:
        app: {{ $relname }}-storage-pool-{{ .name }}
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: "alpha.eksctl.io/nodegroup-name"
                  operator: In
                  values:
                  - storage
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: init-storage-pool
        image: alpine
        command:
          - sleep infinity
        volumeDevices:
          - name: storage-pool
            devicePath: /dev/pool
  volumeClaimTemplates:
    - metadata:
        name: storage-pool
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "openebs-pool-block"
        resources:
          requests:
            storage: {{ $stripesize }}
{{- end }}
