apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Release.Name }}-datasets
parameters:
  scheduler: "VolumeWeighted"
  fstype: 'zfs'
  poolname: 'zfspv-pool'
  compression: 'lz4'
  recordsize: '16k'
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
provisioner: zfs.csi.openebs.io
allowedTopologies:
  - matchLabelExpressions:
      - key: role
        values:
          - storage
